spring:
  application:
    name: datanode-service
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful

grpc:
  server:
    port: ${GRPC_SERVER_PORT:50051}

datanode:
  storage:
    path: ${DATANODE_STORAGE_PATH:/app/data}
  grpc:
    port: ${GRPC_SERVER_PORT:50051}

coordinator:
  host: ${COORDINATOR_HOST:coordinator}
  port: ${COORDINATOR_PORT:50060}
  advertised-host: ${DATANODE_ADVERTISED_HOST:localhost}